#+title: File Struct Help


Five special functions in the ~/.spacemacs file can be used to perform configuration at the beginning and
end of Spacemacs loading process:

+ ~dotspacemacs/init~ is called at the very startup of Spacemacs initialization before layers configuration.
  You should not put any user code in there besides modifying the Spacemacs variable values prefixed with
  dotspacemacs-.
+ ~dotspacemacs/user-init~ is called immediately after dotspacemacs/init, before layer configuration. This
  function is mostly useful for variables that need to be set before packages are loaded.
+ ~dotspacemacs/user-env~ is called before the layers and packages configuration and it is responsible to
  setup environment variables.
+ ~dotspacemacs/layers~ is called at the startup of Spacemacs initialization, this is where you set the
  Spacemacs distribution and declare layers to be used in your configuration. You can also add or exclude
  packages of your choice and tweak some behaviors of Spacemacs loading.
+ ~dotspacemacs/user-config~ is called at the very end of Spacemacs initialization after layers configuration.
  This is the place where most of your configurations should be done. Unless it is explicitly specified that a
  variable should be set before a package is loaded, you should place your code here.
+ ~dotspacemacs/emacs-custom-settings~ is a generated function where all Emacs custom settings are written.
  You should not edit this function. See Custom variables section for more information.
